[32m2025-01-18 15:03:36 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - 7204 - LOGS_CAPTURED - Started capturing logs in process (pid: 7204).
[32m2025-01-18 15:03:36 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - 7204 - dbt_analytics - STEP_START - Started execution of step "dbt_analytics".
[32m2025-01-18 15:03:36 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['db_postgres.scores_movies_users']`.
[32m2025-01-18 15:03:36 -0600[0m - dagster - [34mWARNING[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - dbt_analytics - An error was encountered when creating a handle to the dbt adapter in Dagster.
Traceback (most recent call last):
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster_dbt/core/resource.py", line 672, in cli
    adapter = self._initialize_adapter(cli_vars)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster_dbt/core/resource.py", line 364, in _initialize_adapter
    profile = load_profile(self.project_dir, cli_vars, self.profile, self.target)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/runtime.py", line 71, in load_profile
    profile = Profile.render(
              ^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/profile.py", line 403, in render
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/profile.py", line 360, in from_raw_profiles
    raise DbtProjectError("Could not find profile named '{}'".format(profile_name))
dbt.exceptions.DbtProjectError: Runtime Error
  Could not find profile named 'db_postgres'
[32m2025-01-18 15:03:36 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - dbt_analytics - Copying `/Users/ari/Desktop/github_repos/db_postgres/target/partial_parse.msgpack` to `/Users/ari/Desktop/github_repos/db_postgres/target/dbt_analytics-d19e34c-b75517d/partial_parse.msgpack` to take advantage of partial parsing.
[32m2025-01-18 15:03:36 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - dbt_analytics - Running dbt command: `dbt run --select db_postgres.scores_movies_users`.
[32m2025-01-18 15:03:39 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - 7204 - dbt_analytics - STEP_OUTPUT - Yielded output "scores_movies_users" of type "Nothing". (Type check passed).
[32m2025-01-18 15:03:39 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - 7204 - dbt_analytics - ASSET_MATERIALIZATION - Materialized value scores_movies_users.
[32m2025-01-18 15:03:39 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - dbt_analytics - Finished dbt command: `dbt run --select db_postgres.scores_movies_users`.
[32m2025-01-18 15:03:39 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d19e34cd-7ed4-4979-bd35-d769ae4aaebe - 7204 - dbt_analytics - STEP_SUCCESS - Finished execution of step "dbt_analytics" in 2.7s.
