[32m2025-01-11 16:37:58 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - cc248a3b-972f-4ccb-9e77-53da3d4032e9 - 61820 - LOGS_CAPTURED - Started capturing logs in process (pid: 61820).
[32m2025-01-11 16:37:58 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - cc248a3b-972f-4ccb-9e77-53da3d4032e9 - 61820 - movies - STEP_START - Started execution of step "movies".
[32m2025-01-11 16:37:58 -0600[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - cc248a3b-972f-4ccb-9e77-53da3d4032e9 - 61820 - movies - STEP_FAILURE - Execution of step "movies" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "movies"::

FileNotFoundError: [Errno 2] No such file or directory: ''

Stack Trace:
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 490, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/Desktop/github_repos/rec_sys/rec_sys/assets/movies_users.py", line 24, in movies
    result = pd.read_csv(uri)
             ^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
[0m
